model_type: xgboost
model_path: configs/repm_xgb/nonres_repm331
hedonic_id: 331
target_variable: np.log1p(sqft_price_nonres)
ytransform: np.exp
features:
- stories
- improvement_value
- building_sqft
- vacant_job_spaces
- parcel_sqft
- crime_ucr_rate
- crime_other_rate
- drv_nearest_hospital
- drv_nearest_healthcenter
- drv_nearest_grocery
- drv_nearest_urgentcare
- drv_nearest_library
- drv_nearest_park
- walk_nearest_hospital
- walk_nearest_grocery
- walk_nearest_healthcenter
- walk_nearest_urgentcare
- walk_nearest_library
- walk_nearest_park
- bike_nearest_grocery
- bike_nearest_library
- bike_nearest_park
- building_age
- building_age_gt_50
- building_age_gt_70
- building_age_gt_80
- building_age_gt_90
- building_age_gt_100
- building_age_le_10
- building_age_le_20
- building_age_le_3
- jobs_non_home_based
- mode_income_quartile
- zones_logsum_job_high_income
- zones_logsum_job_mid_income
- zones_logsum_job_low_income
- zones_transit_jobs_50min
- zones_transit_jobs_30min
- zones_a_ln_emp_26min_drive_alone
- zones_a_ln_emp_50min_transit
- zones_a_ln_retail_emp_15min_drive_alone
- bldg_empratio_1
- bldg_jobs_sector_1
- nodes_walk_job_ratio_sector_1
- bldg_empratio_2
- bldg_jobs_sector_2
- nodes_walk_job_ratio_sector_2
- bldg_empratio_3
- bldg_jobs_sector_3
- nodes_walk_job_ratio_sector_3
- bldg_empratio_4
- bldg_jobs_sector_4
- nodes_walk_job_ratio_sector_4
- bldg_empratio_5
- bldg_jobs_sector_5
- nodes_walk_job_ratio_sector_5
- bldg_empratio_6
- bldg_jobs_sector_6
- nodes_walk_job_ratio_sector_6
- bldg_empratio_7
- bldg_jobs_sector_7
- nodes_walk_job_ratio_sector_7
- bldg_empratio_8
- bldg_jobs_sector_8
- nodes_walk_job_ratio_sector_8
- bldg_empratio_9
- bldg_jobs_sector_9
- nodes_walk_job_ratio_sector_9
- bldg_empratio_10
- bldg_jobs_sector_10
- nodes_walk_job_ratio_sector_10
- bldg_empratio_11
- bldg_jobs_sector_11
- nodes_walk_job_ratio_sector_11
- bldg_empratio_12
- bldg_jobs_sector_12
- nodes_walk_job_ratio_sector_12
- bldg_empratio_13
- bldg_jobs_sector_13
- nodes_walk_job_ratio_sector_13
- bldg_empratio_14
- bldg_jobs_sector_14
- nodes_walk_job_ratio_sector_14
- bldg_empratio_15
- nodes_walk_job_ratio_sector_15
- bldg_empratio_16
- bldg_jobs_sector_16
- nodes_walk_job_ratio_sector_16
- bldg_empratio_17
- bldg_jobs_sector_17
- nodes_walk_job_ratio_sector_17
- bldg_empratio_18
- bldg_jobs_sector_18
- nodes_walk_job_ratio_sector_18
- hospitals_walk_near_max90
- health_centers_walk_near_max90
- parks_bike_walk_near_max90
- parks_school_walk_near_max90
- american_job_centers_walk_near_max90
- community_colleges_walk_near_max90
- passenger_train_stations_walk_near_max90
- hospitals_bike_near_max120
- urgent_cares_bike_near_max120
- health_centers_bike_near_max120
- all_healthcare_bike_near_max120
- grocery_stores_bike_near_max120
- parks_local_bike_near_max120
- parks_bike_bike_near_max120
- parks_school_bike_near_max120
- schools_k8_bike_near_max120
- schools_912_bike_near_max120
- pharmacies_bike_near_max120
- childcare_bike_near_max120
- fire_stations_bike_near_max120
- fixed_route_bus_bike_near_max120
- american_job_centers_bike_near_max120
- community_colleges_bike_near_max120
- passenger_airports_bike_near_max120
- passenger_train_stations_bike_near_max120
- all_healthcare_drive_near_max150
- parks_vehicle_drive_near_max150
- schools_k8_drive_near_max150
- schools_912_drive_near_max150
- pharmacies_drive_near_max150
- childcare_drive_near_max150
- fire_stations_drive_near_max150
- american_job_centers_drive_near_max150
- community_colleges_drive_near_max150
- passenger_airports_drive_near_max150
- passenger_train_stations_drive_near_max150
- jobs_walk_cumulative_5min
- jobs_walk_cumulative_10min
- jobs_walk_cumulative_30min
- fixed_route_bus_weekday_walk_10min
- jobs_bike_cumulative_5min
- jobs_bike_cumulative_10min
- jobs_bike_cumulative_15min
- jobs_bike_cumulative_30min
- fixed_route_bus_weekday_bike_10min
- jobs_drive_cumulative_10min
- jobs_drive_cumulative_15min
- jobs_drive_cumulative_20min
- jobs_drive_cumulative_25min
- jobs_drive_cumulative_30min
- jobs_drive_cumulative_45min
- nodes_walk_sum_vacant_residential_units
- nodes_walk_log_sum_residential_units
- nodes_walk_log_sum_nonresidential_units
- nodes_walk_ave_lot_sqft
- nodes_walk_households
- nodes_walk_large_hhs
- nodes_walk_young_hhs
- nodes_walk_senior_hhs
- nodes_walk_lowinc_hhs
- nodes_walk_highinc_hhs
- nodes_walk_race_1_hhs
- nodes_walk_race_2_hhs
- nodes_walk_race_3_hhs
- nodes_walk_race_4_hhs
- nodes_walk_hhs_with_children
- nodes_walk_hhsize
- nodes_walk_ave_income
- nodes_walk_max_industrial_far
- nodes_walk_max_office_far
- nodes_walk_max_retail_far
- nodes_walk_max_medical_far
- nodes_walk_jobs
- nodes_walk_retail_jobs
- nodes_walk_sector1_jobs
- nodes_walk_sector2_jobs
- nodes_walk_sector3_jobs
- nodes_walk_sector4_jobs
- nodes_walk_sector6_jobs
- nodes_walk_sector7_jobs
- nodes_walk_sector8_jobs
- nodes_walk_sector9_jobs
- nodes_walk_sector10_jobs
- nodes_walk_sector11_jobs
- nodes_walk_sector12_jobs
- nodes_walk_sector13_jobs
- nodes_walk_sector14_jobs
- nodes_walk_sector16_jobs
- nodes_walk_sector17_jobs
- nodes_walk_sector18_jobs
- nodes_walk_residential
- nodes_walk_retail
- nodes_walk_office
- nodes_walk_industrial
- nodes_walk_medical
- nodes_walk_entertainment
- nodes_walk_quarter_mile_to_transit
- nodes_walk_log_15min_retail_jobs
- nodes_walk_log_15min_shopping_jobs
- nodes_walk_log_30min_retail_jobs
- nodes_walk_log_30min_shopping_jobs
- nodes_walk_ave_unit_sqft
- nodes_walk_node_r1500_acre
- nodes_walk_vacancy_750m
- nodes_walk_ln_popden
- nodes_walk_percent_high_income
- nodes_walk_percent_mid_income
- nodes_walk_percent_low_income
- nodes_walk_percent_race1
- nodes_walk_percent_race2
- nodes_walk_percent_race3
- nodes_walk_percent_race4
- nodes_walk_percent_hh_with_children
- nodes_walk_housing_cost
- nodes_walk_percent_large_hhs
- nodes_walk_percent_young_hhs
- nodes_walk_percent_senior_hhs
- nodes_drv_log_sum_15min_jobs
- nodes_drv_log_sum_10min_pop
- nodes_drv_log_sum_20min_pop
- nodes_drv_log_sum_15min_retail_jobs
- nodes_drv_elem_school_perf
fit_rsquared: 0.7997327696473159
sample_size: 2131
