model_type: xgboost
model_path: configs/repm_xgb/res_repm9383
hedonic_id: 9383
target_variable: np.log1p(sqft_price_res)
ytransform: np.exp
features:
- nodes_walk_max_retail_far
- nodes_drv_elem_school_perf
- nodes_drv_log_sum_30min_jobs
- nodes_drv_log_sum_15min_jobs
- bike_nearest_grocery
- nodes_walk_percent_race3
- nodes_walk_percent_race2
- drv_nearest_healthcenter
- nodes_walk_max_office_far
- nodes_walk_max_industrial_far
- nodes_walk_hhs_with_children
- nodes_walk_race_2_hhs
- nodes_walk_highinc_hhs
- nodes_walk_max_medical_far
- nodes_walk_sector12_jobs
- nodes_walk_sector11_jobs
- nodes_walk_sector10_jobs
- nodes_walk_sector9_jobs
- nodes_walk_sector7_jobs
- nodes_walk_young_hhs
- nodes_walk_households
- nodes_walk_population
- nodes_walk_log_sum_residential_units
- jobs_drive_gravity_90min
- jobs_drive_cumulative_45min
- jobs_drive_cumulative_25min
- jobs_drive_cumulative_20min
- building_age_gt_100
- bldg_empratio_6
- bldg_empratio_5
- bldg_jobs_sector_4
- bldg_empratio_4
- bldg_empratio_2
- nodes_walk_retail_jobs
- bldg_empratio_1
- zones_a_ln_emp_26min_drive_alone
- mode_income_quartile
- building_age_le_3
- building_age_le_20
- building_age_le_10
- bldg_jobs_sector_2
- building_age_gt_90
- building_age_gt_70
- building_age_gt_50
- bike_nearest_park
- bike_nearest_library
- walk_nearest_library
- walk_nearest_urgentcare
- walk_nearest_hospital
- drv_nearest_park
- nodes_drv_log_sum_20min_pop
- nodes_walk_sector2_jobs
- nodes_walk_sector1_jobs
- nodes_walk_job_ratio_sector_14
- nodes_walk_office
- bldg_jobs_sector_6
- nodes_walk_job_ratio_sector_12
- bldg_jobs_sector_12
- bldg_empratio_12
- nodes_walk_entertainment
- bldg_jobs_sector_10
- bldg_empratio_10
- nodes_walk_log_15min_retail_jobs
- bldg_jobs_sector_9
- nodes_walk_log_30min_retail_jobs
- bldg_jobs_sector_14
- nodes_walk_job_ratio_sector_13
- bldg_empratio_14
- nodes_walk_job_ratio_sector_7
- nodes_walk_job_ratio_sector_8
- schools_912_drive_near_max150
- zones_a_ln_retail_emp_15min_drive_alone
- nodes_walk_race_3_hhs
- pharmacies_walk_near_max90
- nodes_walk_percent_mid_income
- schools_912_walk_near_max90
- fire_stations_bike_near_max120
- nodes_walk_ave_income
- childcare_drive_near_max150
- parks_school_walk_near_max90
- nodes_walk_job_ratio_sector_5
- nodes_walk_node_r1500_acre
- nodes_walk_job_ratio_sector_11
- nodes_walk_large_hhs
- nodes_walk_sector4_jobs
- nodes_walk_percent_low_income
- community_colleges_drive_near_max150
- nodes_walk_residential
- nodes_walk_sector3_jobs
- walk_nearest_grocery
- nodes_walk_hhsize
- bldg_empratio_9
- stories
- nodes_walk_percent_high_income
- nodes_walk_retail
- all_healthcare_bike_near_max120
- jobs_walk_cumulative_10min
- nodes_walk_job_ratio_sector_15
- fixed_route_bus_bike_near_max120
- nodes_drv_log_sum_10min_pop
- nodes_walk_percent_large_hhs
- vacant_residential_units
- nodes_walk_race_4_hhs
- walk_nearest_park
- nodes_walk_job_ratio_sector_2
- nodes_walk_ln_popden
- drv_nearest_hospital
- nodes_walk_job_ratio_sector_9
- nodes_walk_job_ratio_sector_1
- jobs_bike_cumulative_30min
- nodes_walk_job_ratio_sector_16
- nodes_walk_sum_vacant_residential_units
- nodes_walk_ave_unit_sqft
- nodes_walk_vacancy_750m
- nodes_walk_percent_senior_hhs
- nodes_walk_job_ratio_sector_6
- jobs_walk_cumulative_5min
- nodes_walk_job_ratio_sector_18
- drv_nearest_grocery
- nodes_walk_percent_race1
- parks_local_school_bike_near_max120
- nodes_walk_industrial
- drv_nearest_library
- land_area
- community_colleges_bike_near_max120
- parcel_sqft
- nodes_walk_percent_hh_with_children
- nodes_walk_job_ratio_sector_4
- nodes_walk_housing_cost
- nodes_walk_ave_lot_sqft
- nodes_walk_job_ratio_sector_17
- sqft_per_unit
- parks_bike_bike_near_max120
- nodes_walk_job_ratio_sector_3
- nodes_walk_log_sum_nonresidential_units
- childcare_bike_near_max120
- nodes_walk_percent_race4
- jobs_bike_cumulative_5min
- nodes_walk_senior_hhs
- building_sqft
- nodes_walk_job_ratio_sector_10
- schools_k8_bike_near_max120
- nodes_walk_sector6_jobs
- nodes_walk_percent_young_hhs
- nodes_walk_sector18_jobs
- building_age
- nodes_walk_sector8_jobs
- nodes_walk_medical
- improvement_value
- crime_other_rate
fit_rsquared: 0.9526867731324861
sample_size: 491
