model_type: xgboost
model_path: configs/repm_xgb/nonres_repm11531
hedonic_id: 11531
target_variable: np.log1p(sqft_price_nonres)
ytransform: np.exp
features:
- parks_vehicle_drive_near_max150
- libraries_drive_near_max150
- passenger_train_stations_bike_near_max120
- passenger_airports_bike_near_max120
- nodes_walk_race_4_hhs
- nodes_walk_race_2_hhs
- nodes_walk_senior_hhs
- nodes_walk_large_hhs
- health_centers_bike_near_max120
- urgent_cares_bike_near_max120
- nodes_walk_quarter_mile_to_transit
- zones_a_ln_emp_50min_transit
- zones_transit_jobs_30min
- zones_transit_jobs_50min
- zones_transit_jobs_60min
- nodes_walk_job_ratio_sector_8
- building_age_le_3
- building_age_le_20
- building_age_le_10
- building_age_gt_100
- building_age_gt_80
- nodes_walk_log_30min_retail_jobs
- nodes_walk_log_15min_shopping_jobs
- nodes_walk_log_15min_retail_jobs
- zones_logsum_job_low_income
- nodes_walk_percent_high_income
- walk_nearest_urgentcare
- walk_nearest_healthcenter
- walk_nearest_grocery
- walk_nearest_hospital
- drv_nearest_library
- nodes_drv_log_sum_15min_jobs
- nodes_walk_percent_senior_hhs
- nodes_walk_percent_young_hhs
- crime_other_rate
- jobs_drive_cumulative_15min
- fixed_route_bus_weekday_bike_10min
- jobs_bike_cumulative_10min
- zones_a_ln_retail_emp_15min_drive_alone
- bldg_empratio_8
- nodes_walk_job_ratio_sector_7
- bldg_empratio_7
- nodes_walk_sector10_jobs
- nodes_walk_sector9_jobs
- nodes_walk_sector8_jobs
- nodes_walk_sector2_jobs
- bldg_jobs_sector_6
- bldg_empratio_6
- nodes_walk_job_ratio_sector_5
- bldg_jobs_sector_5
- bldg_jobs_sector_4
- nodes_walk_retail
- nodes_walk_residential
- nodes_walk_sector17_jobs
- nodes_walk_sector15_jobs
- bldg_empratio_1
- bldg_jobs_sector_2
- nodes_walk_sector14_jobs
- nodes_walk_sector13_jobs
- nodes_walk_sector18_jobs
- mode_income_quartile
- parks_school_bike_near_max120
- jobs_non_home_based
- nodes_walk_job_ratio_sector_12
- nodes_walk_highinc_hhs
- pharmacies_drive_near_max150
- nodes_drv_log_sum_10min_pop
- nodes_walk_job_ratio_sector_4
- parks_bike_bike_near_max120
- nodes_walk_sector1_jobs
- nodes_walk_ave_unit_sqft
- fire_stations_bike_near_max120
- nodes_walk_sector6_jobs
- nodes_walk_job_ratio_sector_13
- nodes_walk_hhsize
- nodes_walk_sector12_jobs
- stories
- nodes_walk_max_retail_far
- nodes_drv_log_sum_30min_jobs
- nodes_drv_elem_school_perf
- bldg_empratio_12
- nodes_walk_job_ratio_sector_1
- nodes_walk_sum_vacant_residential_units
- nodes_walk_job_ratio_sector_6
- nodes_walk_percent_race4
- jobs_bike_cumulative_30min
- all_healthcare_drive_near_max150
- fire_stations_drive_near_max150
- nodes_walk_job_ratio_sector_3
- nodes_walk_sector3_jobs
- bldg_empratio_4
- crime_ucr_rate
- jobs_bike_cumulative_5min
- drv_nearest_healthcenter
- nodes_walk_ave_lot_sqft
- walk_nearest_park
- nodes_walk_job_ratio_sector_16
- zones_a_ln_emp_26min_drive_alone
- zones_logsum_job_high_income
- nodes_walk_entertainment
- american_job_centers_bike_near_max120
- drv_nearest_grocery
- community_colleges_bike_near_max120
- bldg_empratio_3
- bldg_jobs_sector_3
- nodes_walk_percent_race3
- drv_nearest_hospital
- grocery_stores_bike_near_max120
- nodes_walk_percent_hh_with_children
- nodes_walk_vacancy_750m
- jobs_walk_cumulative_10min
- schools_k8_bike_near_max120
- nodes_walk_race_3_hhs
- bldg_empratio_5
- urgent_cares_walk_near_max90
- nodes_walk_percent_mid_income
- nodes_walk_job_ratio_sector_11
- jobs_bike_cumulative_15min
- childcare_drive_near_max150
- nodes_walk_housing_cost
- land_area
- bldg_empratio_2
- building_sqft
- all_healthcare_bike_near_max120
- nodes_walk_job_ratio_sector_17
- parcel_sqft
- nodes_walk_ave_income
- health_centers_walk_near_max90
- nodes_walk_node_r1500_acre
- passenger_train_stations_drive_near_max150
- jobs_walk_cumulative_5min
- nodes_walk_hhs_with_children
- improvement_value
- nodes_walk_job_ratio_sector_2
- schools_912_bike_near_max120
- nodes_walk_ln_popden
- drv_nearest_park
- nodes_walk_sector4_jobs
- nodes_walk_sector16_jobs
- parks_bike_walk_near_max90
- drv_nearest_urgentcare
- bike_nearest_library
- building_age
- bike_nearest_grocery
- pharmacies_bike_near_max120
- childcare_bike_near_max120
- nodes_walk_percent_large_hhs
- jobs_drive_cumulative_10min
- libraries_bike_near_max120
- nodes_walk_industrial
fit_rsquared: 0.548791461236362
sample_size: 242
