model_type: xgboost
model_path: configs/repm_xgb/nonres_repm94
hedonic_id: 94
target_variable: np.log1p(sqft_price_nonres)
ytransform: np.exp
features:
- nodes_walk_sector6_jobs
- schools_k8_bike_near_max120
- nodes_walk_sector7_jobs
- parks_school_bike_near_max120
- nodes_walk_sector8_jobs
- bike_nearest_library
- zones_logsum_job_low_income
- zones_logsum_pop_low_income
- zones_logsum_pop_mid_income
- mode_income_quartile
- building_age_le_20
- building_age_gt_100
- building_age_gt_90
- building_age_gt_80
- building_age_gt_70
- building_age_gt_50
- nodes_walk_ln_popden
- bike_nearest_park
- bldg_empratio_6
- bike_nearest_grocery
- nodes_walk_percent_high_income
- walk_nearest_urgentcare
- nodes_drv_log_sum_15min_jobs
- walk_nearest_grocery
- walk_nearest_hospital
- nodes_walk_percent_large_hhs
- nodes_walk_percent_hh_with_children
- nodes_walk_percent_race4
- nodes_walk_percent_race3
- vacant_residential_units
- drv_nearest_library
- bldg_empratio_4
- bldg_jobs_sector_2
- bldg_empratio_3
- bldg_empratio_1
- nodes_walk_quarter_mile_to_transit
- zones_a_ln_emp_50min_transit
- bldg_empratio_5
- bldg_jobs_sector_5
- zones_transit_jobs_50min
- nodes_walk_log_30min_retail_jobs
- nodes_walk_senior_hhs
- nodes_walk_race_2_hhs
- bldg_empratio_2
- nodes_walk_job_ratio_sector_10
- drv_nearest_park
- passenger_train_stations_bike_near_max120
- nodes_drv_elem_school_perf
- zones_a_ln_retail_emp_15min_drive_alone
- drv_nearest_grocery
- nodes_walk_job_ratio_sector_13
- jobs_bike_cumulative_10min
- crime_ucr_rate
- nodes_walk_hhsize
- zones_transit_jobs_30min
- nodes_walk_entertainment
- jobs_non_home_based
- nodes_walk_sector4_jobs
- american_job_centers_walk_near_max90
- fire_stations_bike_near_max120
- nodes_walk_vacancy_750m
- parks_school_walk_near_max90
- nodes_walk_job_ratio_sector_16
- nodes_walk_max_retail_far
- nodes_walk_job_ratio_sector_1
- nodes_walk_young_hhs
- jobs_drive_cumulative_15min
- stories
- childcare_bike_near_max120
- schools_912_drive_near_max150
- nodes_walk_job_ratio_sector_4
- nodes_walk_percent_senior_hhs
- residential_sqft
- nodes_walk_hhs_with_children
- nodes_walk_job_ratio_sector_9
- walk_nearest_park
- jobs_walk_cumulative_5min
- drv_nearest_healthcenter
- nodes_walk_job_ratio_sector_17
- nodes_walk_office
- nodes_walk_housing_cost
- crime_other_rate
- fixed_route_bus_walk_near_max90
- parks_bike_walk_near_max90
- fire_stations_drive_near_max150
- nodes_walk_job_ratio_sector_12
- nodes_walk_log_15min_retail_jobs
- health_centers_bike_near_max120
- nodes_walk_large_hhs
- nodes_walk_job_ratio_sector_6
- zones_logsum_job_mid_income
- parks_bike_bike_near_max120
- pharmacies_bike_near_max120
- nodes_walk_retail_jobs
- nodes_walk_job_ratio_sector_3
- nodes_walk_sector18_jobs
- nodes_walk_percent_race1
- nodes_walk_node_r1500_acre
- nodes_walk_max_office_far
- nodes_drv_log_sum_10min_pop
- all_healthcare_walk_near_max90
- parks_local_school_bike_near_max120
- all_healthcare_bike_near_max120
- health_centers_walk_near_max90
- urgent_cares_walk_near_max90
- nodes_walk_job_ratio_sector_2
- land_area
- zones_transit_jobs_60min
- nodes_walk_percent_young_hhs
- nodes_walk_sector16_jobs
- nodes_walk_sector9_jobs
- nodes_walk_log_sum_nonresidential_units
- fixed_route_bus_bike_near_max120
- fixed_route_bus_weekend_walk_10min
- building_age
- nodes_walk_job_ratio_sector_5
- schools_k8_drive_near_max150
- nodes_walk_sector3_jobs
- pharmacies_walk_near_max90
- parks_vehicle_drive_near_max150
- nodes_walk_sum_vacant_residential_units
- nodes_walk_highinc_hhs
- zones_logsum_job_high_income
- passenger_airports_bike_near_max120
- hospitals_walk_near_max90
- vacant_job_spaces
- nodes_walk_log_sum_residential_units
- job_spaces
- schools_912_bike_near_max120
- urgent_cares_bike_near_max120
- nodes_walk_midinc_hhs
- drv_nearest_urgentcare
- walk_nearest_healthcenter
- nodes_walk_medical
- drv_nearest_hospital
- nodes_walk_sector12_jobs
- nodes_walk_job_ratio_sector_11
- nodes_walk_sector17_jobs
- nodes_walk_race_1_hhs
- nodes_walk_percent_mid_income
- building_sqft
- improvement_value
- walk_nearest_library
- nodes_walk_percent_low_income
- nodes_walk_ave_unit_sqft
- parcel_sqft
- nodes_walk_race_3_hhs
- nodes_walk_max_industrial_far
- american_job_centers_drive_near_max150
- nodes_walk_retail
fit_rsquared: 0.78978242493955
sample_size: 243
