model_type: xgboost
model_path: configs/repm_xgb/nonres_repm11533
hedonic_id: 11533
target_variable: np.log1p(sqft_price_nonres)
ytransform: np.exp
features:
- nodes_walk_medical
- nodes_walk_entertainment
- nodes_walk_quarter_mile_to_transit
- nodes_walk_log_15min_retail_jobs
- nodes_walk_sector14_jobs
- nodes_walk_log_30min_retail_jobs
- nodes_walk_log_30min_shopping_jobs
- nodes_walk_percent_mid_income
- building_sqft
- nodes_walk_percent_race1
- nodes_drv_log_sum_15min_jobs
- nodes_drv_log_sum_30min_jobs
- nodes_walk_max_medical_far
- nodes_walk_households
- nodes_walk_highinc_hhs
- nodes_walk_race_2_hhs
- nodes_walk_race_4_hhs
- nodes_walk_ave_income
- nodes_walk_max_industrial_far
- nodes_walk_max_office_far
- nodes_walk_max_retail_far
- schools_912_bike_near_max120
- nodes_walk_retail_jobs
- nodes_walk_sector2_jobs
- nodes_walk_sector4_jobs
- nodes_walk_sector6_jobs
- nodes_walk_sector7_jobs
- nodes_walk_sector10_jobs
- nodes_walk_sector13_jobs
- building_age_le_3
- bldg_jobs_sector_3
- bldg_empratio_3
- nodes_walk_job_ratio_sector_2
- bldg_jobs_sector_2
- bldg_empratio_1
- zones_a_ln_retail_emp_15min_drive_alone
- zones_a_ln_emp_50min_transit
- walk_nearest_hospital
- stories
- nodes_walk_percent_race2
- nodes_walk_percent_race4
- zones_transit_jobs_50min
- mode_income_quartile
- nodes_walk_housing_cost
- nodes_walk_job_ratio_sector_13
- building_age_le_20
- building_age_le_10
- building_age_gt_80
- building_age_gt_70
- building_age_gt_50
- nodes_walk_percent_large_hhs
- bike_nearest_park
- bike_nearest_library
- bike_nearest_grocery
- walk_nearest_park
- walk_nearest_grocery
- walk_nearest_library
- walk_nearest_healthcenter
- walk_nearest_urgentcare
- bldg_empratio_10
- bldg_jobs_sector_4
- bldg_jobs_sector_6
- bldg_empratio_6
- nodes_walk_job_ratio_sector_5
- nodes_walk_job_ratio_sector_7
- bldg_empratio_8
- nodes_walk_job_ratio_sector_8
- bldg_empratio_9
- bldg_jobs_sector_9
- bldg_jobs_sector_10
- nodes_walk_job_ratio_sector_10
- nodes_walk_job_ratio_sector_11
- bldg_empratio_12
- bldg_jobs_sector_12
- nodes_walk_percent_low_income
- bldg_empratio_5
- nodes_walk_sector1_jobs
- nodes_walk_job_ratio_sector_16
- bldg_empratio_16
- bldg_empratio_4
- schools_k8_bike_near_max120
- bldg_jobs_sector_5
- parks_bike_bike_near_max120
- job_spaces
- nodes_walk_log_sum_residential_units
- nodes_walk_vacancy_750m
- nodes_walk_job_ratio_sector_1
- nodes_walk_hhsize
- nodes_walk_sum_vacant_residential_units
- schools_k8_drive_near_max150
- nodes_walk_residential
- nodes_walk_log_sum_nonresidential_units
- nodes_walk_node_r1500_acre
- nodes_walk_job_ratio_sector_3
- nodes_drv_log_sum_10min_pop
- jobs_walk_cumulative_5min
- bldg_empratio_2
- childcare_drive_near_max150
- nodes_drv_elem_school_perf
- crime_other_rate
- drv_nearest_library
- nodes_walk_job_ratio_sector_17
- drv_nearest_urgentcare
- nodes_walk_young_hhs
- crime_ucr_rate
- nodes_walk_senior_hhs
- drv_nearest_park
- nodes_walk_ave_unit_sqft
- nodes_walk_hhs_with_children
- nodes_walk_sector17_jobs
- nodes_walk_percent_young_hhs
- nodes_walk_large_hhs
- nodes_walk_percent_senior_hhs
- drv_nearest_hospital
- parcel_sqft
- zones_a_ln_emp_26min_drive_alone
- nodes_walk_sector12_jobs
- parks_bike_walk_near_max90
- nodes_walk_job_ratio_sector_6
- nodes_walk_sector3_jobs
- nodes_walk_retail
- passenger_train_stations_drive_near_max150
- nodes_walk_percent_hh_with_children
- nodes_walk_sector8_jobs
- nodes_walk_job_ratio_sector_4
- all_healthcare_drive_near_max150
- nodes_walk_race_3_hhs
- vacant_job_spaces
- jobs_walk_cumulative_10min
- parks_vehicle_drive_near_max150
- jobs_drive_cumulative_45min
- drv_nearest_grocery
- jobs_drive_cumulative_20min
- jobs_non_home_based
- nodes_walk_ave_lot_sqft
- nodes_walk_job_ratio_sector_9
- land_area
- jobs_bike_cumulative_30min
- building_age
- nodes_walk_job_ratio_sector_12
- pharmacies_drive_near_max150
- nodes_walk_ln_popden
- childcare_bike_near_max120
- health_centers_walk_near_max90
- nodes_walk_sector9_jobs
- drv_nearest_healthcenter
- improvement_value
- nodes_walk_percent_high_income
- nodes_walk_percent_race3
- nodes_walk_industrial
fit_rsquared: 0.6435987246577113
sample_size: 286
