model_type: xgboost
model_path: configs/repm_xgb/nonres_repm11523
hedonic_id: 11523
target_variable: np.log1p(sqft_price_nonres)
ytransform: np.exp
features:
- nodes_walk_log_sum_nonresidential_units
- nodes_walk_log_sum_residential_units
- bldg_jobs_sector_7
- jobs_drive_cumulative_25min
- jobs_drive_cumulative_20min
- jobs_drive_cumulative_15min
- fixed_route_bus_weekday_bike_10min
- pharmacies_bike_near_max120
- parks_school_bike_near_max120
- parks_local_bike_near_max120
- community_colleges_walk_near_max90
- nodes_walk_race_3_hhs
- nodes_walk_highinc_hhs
- nodes_walk_young_hhs
- schools_k8_drive_near_max150
- zones_a_ln_emp_50min_transit
- nodes_walk_ave_unit_sqft
- nodes_walk_log_30min_retail_jobs
- nodes_walk_log_15min_retail_jobs
- nodes_walk_quarter_mile_to_transit
- nodes_walk_entertainment
- building_age_le_20
- building_age_le_10
- jobs_walk_cumulative_5min
- passenger_train_stations_drive_near_max150
- fire_stations_drive_near_max150
- zones_transit_jobs_30min
- all_healthcare_drive_near_max150
- passenger_train_stations_bike_near_max120
- passenger_airports_bike_near_max120
- building_age_gt_100
- building_age_gt_90
- building_age_gt_80
- fixed_route_bus_weekday_walk_10min
- building_age_gt_50
- bike_nearest_park
- bike_nearest_grocery
- nodes_walk_retail
- nodes_walk_sector11_jobs
- nodes_walk_sector7_jobs
- nodes_drv_log_sum_30min_jobs
- nodes_walk_sector6_jobs
- nodes_walk_sector4_jobs
- nodes_walk_sector3_jobs
- bldg_jobs_sector_6
- bldg_empratio_6
- bldg_empratio_5
- nodes_walk_job_ratio_sector_4
- bldg_jobs_sector_4
- bldg_empratio_2
- nodes_walk_residential
- nodes_walk_sector18_jobs
- nodes_walk_sector14_jobs
- nodes_walk_sector13_jobs
- bldg_empratio_4
- bldg_jobs_sector_3
- bldg_empratio_3
- walk_nearest_hospital
- crime_ucr_rate
- nodes_walk_vacancy_750m
- nodes_walk_percent_race4
- nodes_walk_sector10_jobs
- stories
- nodes_walk_job_ratio_sector_15
- nodes_walk_sector2_jobs
- nodes_walk_job_ratio_sector_7
- drv_nearest_healthcenter
- drv_nearest_hospital
- nodes_walk_node_r1500_acre
- nodes_walk_ln_popden
- nodes_walk_percent_large_hhs
- walk_nearest_grocery
- nodes_walk_large_hhs
- schools_912_bike_near_max120
- drv_nearest_park
- fire_stations_bike_near_max120
- walk_nearest_park
- bike_nearest_library
- parks_school_walk_near_max90
- hospitals_walk_near_max90
- zones_a_ln_emp_26min_drive_alone
- nodes_walk_sum_vacant_residential_units
- bldg_empratio_16
- parks_bike_walk_near_max90
- nodes_walk_sector8_jobs
- building_age
- nodes_walk_senior_hhs
- all_healthcare_bike_near_max120
- fixed_route_bus_walk_near_max90
- nodes_walk_percent_senior_hhs
- nodes_walk_sector16_jobs
- mode_income_quartile
- nodes_walk_job_ratio_sector_5
- drv_nearest_grocery
- nodes_walk_race_4_hhs
- nodes_walk_race_2_hhs
- nodes_walk_job_ratio_sector_6
- walk_nearest_urgentcare
- nodes_walk_job_ratio_sector_1
- nodes_walk_percent_young_hhs
- nodes_walk_percent_race1
- nodes_walk_job_ratio_sector_2
- nodes_walk_hhsize
- nodes_walk_housing_cost
- nodes_walk_medical
- walk_nearest_library
- bldg_empratio_10
- childcare_drive_near_max150
- drv_nearest_library
- nodes_walk_job_ratio_sector_17
- zones_transit_jobs_50min
- nodes_walk_percent_race3
- bldg_jobs_sector_5
- nodes_walk_job_ratio_sector_3
- nodes_walk_job_ratio_sector_9
- nodes_walk_retail_jobs
- land_area
- nodes_walk_ave_lot_sqft
- sqft_per_unit
- bldg_empratio_12
- american_job_centers_walk_near_max90
- bldg_empratio_9
- jobs_non_home_based
- american_job_centers_bike_near_max120
- nodes_walk_percent_mid_income
- bldg_jobs_sector_9
- nodes_walk_industrial
- nodes_drv_log_sum_10min_pop
- parks_bike_bike_near_max120
- schools_912_drive_near_max150
- nodes_walk_job_ratio_sector_18
- schools_k8_bike_near_max120
- bldg_jobs_sector_16
- nodes_drv_elem_school_perf
- nodes_walk_job_ratio_sector_10
- nodes_walk_job_ratio_sector_8
- bldg_jobs_sector_2
- zones_a_ln_retail_emp_15min_drive_alone
- community_colleges_bike_near_max120
- nodes_walk_job_ratio_sector_16
- nodes_walk_ave_income
- nodes_walk_job_ratio_sector_14
- drv_nearest_urgentcare
- nodes_walk_percent_hh_with_children
- improvement_value
- building_sqft
- childcare_bike_near_max120
- zones_logsum_job_low_income
- vacant_job_spaces
- nodes_walk_office
fit_rsquared: 0.8474316484887516
sample_size: 408
