model_type: xgboost
model_path: configs/repm_xgb/nonres_repm9331
hedonic_id: 9331
target_variable: np.log1p(sqft_price_nonres)
ytransform: np.exp
features:
- nodes_walk_households
- nodes_walk_ave_lot_sqft
- bldg_empratio_16
- nodes_walk_sum_vacant_residential_units
- jobs_drive_cumulative_45min
- jobs_drive_cumulative_20min
- jobs_drive_cumulative_15min
- nodes_walk_jobs
- fixed_route_bus_weekday_bike_10min
- jobs_bike_cumulative_30min
- nodes_walk_retail_jobs
- nodes_walk_sector1_jobs
- fixed_route_bus_weekday_walk_10min
- nodes_walk_sector7_jobs
- nodes_walk_sector9_jobs
- passenger_train_stations_drive_near_max150
- american_job_centers_drive_near_max150
- building_age_le_20
- drv_nearest_healthcenter
- bldg_jobs_sector_5
- nodes_walk_percent_young_hhs
- bldg_empratio_5
- bike_nearest_library
- bldg_jobs_sector_4
- nodes_walk_percent_senior_hhs
- nodes_walk_percent_race2
- nodes_walk_percent_race3
- building_age_le_10
- nodes_walk_percent_hh_with_children
- nodes_drv_log_sum_30min_jobs
- building_age_le_3
- mode_income_quartile
- zones_a_ln_retail_emp_15min_drive_alone
- nodes_drv_log_sum_10min_pop
- bldg_empratio_1
- walk_nearest_park
- bldg_jobs_sector_1
- bldg_jobs_sector_2
- nodes_walk_node_r1500_acre
- drv_nearest_library
- nodes_walk_ave_unit_sqft
- building_age_gt_50
- building_age_gt_70
- walk_nearest_hospital
- walk_nearest_grocery
- building_age_gt_80
- bldg_jobs_sector_9
- walk_nearest_urgentcare
- bldg_jobs_sector_8
- walk_nearest_library
- bldg_empratio_8
- nodes_walk_job_ratio_sector_7
- bldg_empratio_7
- building_age_gt_100
- bldg_jobs_sector_6
- bldg_empratio_6
- nodes_walk_job_ratio_sector_5
- bike_nearest_park
- bike_nearest_grocery
- drv_nearest_park
- nodes_walk_job_ratio_sector_1
- stories
- libraries_bike_near_max120
- jobs_drive_cumulative_25min
- parks_local_bike_near_max120
- jobs_drive_gravity_90min
- bldg_jobs_sector_12
- nodes_walk_sector12_jobs
- pharmacies_drive_near_max150
- nodes_walk_race_2_hhs
- zones_a_ln_emp_26min_drive_alone
- crime_ucr_rate
- nodes_walk_residential
- fire_stations_bike_near_max120
- nodes_walk_log_sum_nonresidential_units
- nodes_walk_job_ratio_sector_13
- nodes_walk_percent_race4
- nodes_walk_job_ratio_sector_4
- fire_stations_drive_near_max150
- nodes_walk_job_ratio_sector_10
- all_healthcare_walk_near_max90
- bldg_empratio_4
- bldg_empratio_11
- parks_bike_bike_near_max120
- hospitals_walk_near_max90
- nodes_walk_sector6_jobs
- bldg_empratio_9
- jobs_non_home_based
- drv_nearest_grocery
- childcare_bike_near_max120
- nodes_walk_job_ratio_sector_9
- bldg_empratio_10
- bldg_empratio_2
- nodes_walk_sector10_jobs
- nodes_walk_sector17_jobs
- nodes_walk_percent_mid_income
- nodes_drv_log_sum_15min_jobs
- parks_school_walk_near_max90
- bldg_empratio_12
- crime_other_rate
- parks_local_school_bike_near_max120
- schools_912_bike_near_max120
- nodes_walk_job_ratio_sector_16
- nodes_walk_job_ratio_sector_14
- nodes_walk_job_ratio_sector_3
- grocery_stores_bike_near_max120
- nodes_walk_job_ratio_sector_8
- nodes_walk_job_ratio_sector_17
- nodes_walk_housing_cost
- nodes_walk_sector3_jobs
- nodes_walk_retail
- jobs_walk_cumulative_10min
- pharmacies_bike_near_max120
- nodes_walk_ln_popden
- parks_school_bike_near_max120
- schools_k8_bike_near_max120
- nodes_walk_percent_high_income
- nodes_walk_young_hhs
- nodes_walk_sector8_jobs
- american_job_centers_bike_near_max120
- bldg_jobs_sector_3
- nodes_walk_percent_low_income
- jobs_bike_cumulative_10min
- nodes_walk_job_ratio_sector_12
- nodes_walk_job_ratio_sector_6
- drv_nearest_hospital
- jobs_drive_cumulative_10min
- nodes_walk_job_ratio_sector_2
- bldg_empratio_3
- fixed_route_bus_bike_near_max120
- nodes_walk_sector4_jobs
- nodes_walk_sector2_jobs
- bldg_jobs_sector_10
- nodes_walk_vacancy_750m
- nodes_walk_percent_large_hhs
- nodes_drv_log_sum_20min_pop
- nodes_walk_ave_income
- parcel_sqft
- building_sqft
- building_age
- jobs_bike_cumulative_5min
- vacant_job_spaces
- community_colleges_drive_near_max150
- jobs_bike_cumulative_15min
- jobs_walk_cumulative_5min
- improvement_value
- health_centers_drive_near_max150
- childcare_drive_near_max150
- nodes_drv_elem_school_perf
- nodes_walk_industrial
fit_rsquared: 0.8046563945180336
sample_size: 442
