model_type: xgboost
model_path: configs/repm_xgb/nonres_repm32
hedonic_id: 32
target_variable: np.log1p(sqft_price_nonres)
ytransform: np.exp
features:
- zones_a_ln_retail_emp_15min_drive_alone
- zones_a_ln_emp_50min_transit
- nodes_walk_percent_large_hhs
- zones_transit_jobs_30min
- zones_transit_jobs_50min
- nodes_walk_percent_young_hhs
- nodes_walk_vacancy_750m
- walk_nearest_library
- nodes_drv_log_sum_10min_pop
- nodes_walk_percent_low_income
- bldg_empratio_1
- mode_income_quartile
- nodes_walk_percent_senior_hhs
- drv_nearest_healthcenter
- building_age_le_3
- building_age_gt_50
- building_age_le_20
- building_age_le_10
- building_age_gt_70
- building_age_gt_100
- building_age_gt_80
- nodes_walk_sector15_jobs
- nodes_walk_job_ratio_sector_7
- drv_nearest_library
- bldg_jobs_sector_6
- drv_nearest_park
- walk_nearest_hospital
- bldg_empratio_6
- nodes_walk_job_ratio_sector_5
- bldg_jobs_sector_5
- bldg_empratio_5
- walk_nearest_healthcenter
- nodes_walk_quarter_mile_to_transit
- nodes_drv_elem_school_perf
- nodes_walk_percent_race2
- nodes_walk_percent_race4
- bldg_jobs_sector_3
- nodes_walk_percent_hh_with_children
- nodes_walk_job_ratio_sector_2
- bldg_jobs_sector_2
- bldg_empratio_2
- bldg_empratio_4
- bike_nearest_park
- walk_nearest_grocery
- nodes_walk_housing_cost
- stories
- nodes_drv_log_sum_15min_jobs
- jobs_bike_cumulative_5min
- bldg_empratio_12
- bldg_jobs_sector_4
- bldg_empratio_8
- all_healthcare_drive_near_max150
- hospitals_walk_near_max90
- fixed_route_bus_walk_near_max90
- bike_nearest_library
- hospitals_bike_near_max120
- nodes_walk_sector14_jobs
- nodes_walk_sector16_jobs
- bldg_empratio_10
- nodes_walk_young_hhs
- drv_nearest_grocery
- nodes_walk_job_ratio_sector_18
- nodes_walk_log_15min_retail_jobs
- nodes_walk_max_medical_far
- childcare_bike_near_max120
- nodes_walk_sector2_jobs
- nodes_walk_percent_high_income
- nodes_walk_percent_race3
- jobs_bike_cumulative_30min
- nodes_walk_job_ratio_sector_9
- nodes_walk_job_ratio_sector_13
- nodes_walk_medical
- nodes_walk_ave_income
- drv_nearest_urgentcare
- walk_nearest_urgentcare
- fixed_route_bus_weekday_walk_10min
- bldg_empratio_3
- nodes_walk_percent_mid_income
- american_job_centers_drive_near_max150
- walk_nearest_park
- urgent_cares_bike_near_max120
- nodes_walk_sector18_jobs
- drv_nearest_hospital
- zones_transit_jobs_60min
- fire_stations_drive_near_max150
- nodes_walk_job_ratio_sector_10
- nodes_walk_job_ratio_sector_16
- nodes_walk_sector4_jobs
- nodes_walk_race_1_hhs
- bike_nearest_grocery
- fixed_route_bus_weekday_bike_10min
- zones_logsum_job_low_income
- schools_912_bike_near_max120
- nodes_walk_job_ratio_sector_1
- nodes_walk_max_industrial_far
- nodes_walk_max_office_far
- passenger_train_stations_bike_near_max120
- nodes_walk_log_sum_nonresidential_units
- parks_school_bike_near_max120
- parks_school_walk_near_max90
- parks_local_school_bike_near_max120
- zones_logsum_job_high_income
- jobs_walk_cumulative_5min
- zones_logsum_job_mid_income
- nodes_walk_sector13_jobs
- community_colleges_bike_near_max120
- jobs_drive_cumulative_20min
- nodes_walk_retail_jobs
- jobs_non_home_based
- nodes_walk_entertainment
- schools_912_drive_near_max150
- american_job_centers_bike_near_max120
- nodes_walk_sector17_jobs
- health_centers_bike_near_max120
- nodes_walk_sector12_jobs
- parcel_sqft
- nodes_walk_log_30min_retail_jobs
- nodes_walk_race_2_hhs
- nodes_walk_ln_popden
- fixed_route_bus_bike_near_max120
- improvement_value
- nodes_walk_job_ratio_sector_14
- building_sqft
- crime_ucr_rate
- nodes_walk_node_r1500_acre
- schools_k8_bike_near_max120
- community_colleges_drive_near_max150
- pharmacies_bike_near_max120
- all_healthcare_bike_near_max120
- nodes_walk_residential
- jobs_bike_cumulative_10min
- nodes_walk_job_ratio_sector_4
- nodes_walk_sector9_jobs
- pharmacies_drive_near_max150
- parks_bike_walk_near_max90
- nodes_walk_max_retail_far
- passenger_airports_drive_near_max150
- nodes_walk_job_ratio_sector_6
- crime_other_rate
- all_healthcare_walk_near_max90
- nodes_walk_ave_lot_sqft
- grocery_stores_bike_near_max120
- jobs_drive_cumulative_15min
- nodes_walk_job_ratio_sector_3
- nodes_walk_office
- building_age
- zones_logsum_pop_low_income
- nodes_walk_retail
- nodes_walk_industrial
- nodes_walk_ave_unit_sqft
fit_rsquared: 0.5893016594061364
sample_size: 274
